// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbcmpyoegdslyvghltnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiY21weW9lZ2RzbHl2Z2hsdG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTUxMTksImV4cCI6MjA3NDk3MTExOX0.3qpgN-R5t9ms_Hz3bFpJK2q8vYQ5v2q3ealKqu49r00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});